name: SW_svile
author: svile
description: SkyWars plugin
main: svile\sw\SWmain
version: 0.7dev
api: [3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.1]
load: STARTUP

commands:
 sw:
  description: SkyWars main command
